version: '3.7'
services:
  sheira-provider:
    image: olelarsen/provider
    container_name: sheira-provider
    environment:
      PORT: 3012
    ports:
      - 3012:3012
    networks:
      - sheira-web
    restart: always
networks:
  sheira-web:
    name: sheira-web
    driver: bridge
